//816034693
public class ChatBot {
    private String chatBotName; // name of LLM
    private int numResponsesGenerated; // responses generated by ChatBot
    private static final int messageLimit = 10; // number of messages that can be generated by all chatbots
    private static int messageNumber = 0; // msgs generated by all chatbots

    public ChatBot() {
        chatBotName = "ChatGPT-3.5";
        numResponsesGenerated = 0;
    }

    public ChatBot(int LLMCode) {
        ChatBotGenerator g = new ChatBotGenerator();
        chatBotName = g.generateChatBotLLM(LLMCode);
        numResponsesGenerated = 0;
    }

    public ChatBot(String LLMCode) {
        ChatBotGenerator g = new ChatBotGenerator();    
        chatBotName = g.generateChatBotLLM(LLMCode);
        numResponsesGenerated = 0;
    }

    public String getChatBotName() {
        return chatBotName;
    }

    public int getNumResponsesGenerated() {
        return numResponsesGenerated;
    }

    public static int getMessageLimit() {
        return ChatBot.messageLimit;
    }

    public static int getTotalNumResponsesGenerated() {
        return ChatBot.messageNumber;
    }

    public static int getTotalNumMessagesRemaining() {
        return ChatBot.messageLimit - ChatBot.messageNumber;
    }

    public static boolean limitReached() {
        if (ChatBot.messageLimit == ChatBot.messageNumber)
            return true;
        else
            return false;
    }

    private String generateResponse() {
        String s = "(Message #" + (ChatBot.messageNumber + 1) + ") Response from " + chatBotName
                + ": generatedTextHere";
        ChatBot.messageNumber++;
        numResponsesGenerated++;
        return s;
    }

    public String prompt(String requestMessage) {
        if (ChatBot.limitReached())
            return "Daily Limit Reached. Wait 24 hours to resume chatbot usage";
        else {
            return generateResponse();
        }
    }

    public String toString() {
        String s;
        s = "Chatbot Name: " + chatBotName + " Number Messages used: " + numResponsesGenerated;
        return s;
    }

}
